import React from "react";
import Head from "next/head";
import Navbar from "./navbar";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>SystemQr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid-container">
        <div className="side-layout">
          <Navbar></Navbar>
        </div>
        <main className="main-layout">{children}</main>
      </div>
    </>
  );
}
